## KNN 

### Required Library

In [1]:
import numpy as np
import pandas as pd
import os

from sklearn.model_selection import train_test_split


#os.environ['PATH'] += os.pathsep + 'C:\\Users\\Gnaneeswar\\Desktop\\Praxis\\Python\\graphviz-2.38\\release\\bin'
#os.environ['PATH'].split(os.pathsep)

### Data

In [2]:
#DATA
#Setting the working directory
os.chdir(r"C:\Users\Gnaneeswar\Desktop\Praxis\Python")
#Reading the data
iris = pd.read_csv("iris.csv")

In [3]:
#The first few observtions of the data
iris.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           1           5.1          3.5           1.4          0.2  setosa
1           2           4.9          3.0           1.4          0.2  setosa
2           3           4.7          3.2           1.3          0.2  setosa
3           4           4.6          3.1           1.5          0.2  setosa
4           5           5.0          3.6           1.4          0.2  setosa

In [4]:
import warnings
warnings.filterwarnings("ignore")

In [5]:
def distance (obs,df):
    
    dist=[]

    for i in df.index:
        
        dist.append(np.sqrt(np.sum(((df.loc[i,]-obs)**2).values)))

    return(dist)

In [6]:
def knn(i,df):
    
    # getting the index of the i number of rows which has minimum distance value in ascending order
    
    a=df.sort_values(by="distance",ascending=True).head(i).index.values
    
    # returning the index
    return(a)


### KNN Classifer and Regressor in one function

In [7]:
def runknn(k,X_test,Y_test,X_train,Y_train):

    from scipy import stats
    y_pred=[]

    for i in X_test.index:

        # for each iteration get a copy form X_train
        X_train1=X_train.copy()

        # pick the ith row from test data
        obs1=X_test.loc[i,]

        # computing distance beween ith observation of test data and all observations of train data
        dist= distance(obs1,X_train1)

        #storing computed distance in X_train1
        X_train1.loc[:,"distance"]=dist

        #print(X_train1.head())

        # getting the index of k cases in train data. 
        testidx=knn(k,X_train1)
        
        # if Y_train dtype is object then take mode else take mean
        
        if(Y_train[Y_train.columns[0]].dtypes=="object"):
            
            #taking MODE of values in y_train
            #------------------------------------

            try:
                y_pred.append(stats.mode(Y_train.loc[testidx,"Species"])[0][0])
                
            except:
                
                #in case multiple mode is present,take the first mode
                
                c=Y_train.loc[testidx,"Species"]

                y_pred.append(max(c.values, key=list(c).count))
        
        else:
            #taking MEAN of values in y_train
            #------------------------------------
            
            y_pred.append(np.mean(Y_train.loc[testidx,"Species"])[0][0])
        
    x_test1=X_test.copy()

    #appaending predicted values in x_test1 dataframe
    x_test1["pred"]=y_pred
    
    #appaending actual values in x_test1 dataframe
    x_test1["actual"]=Y_test
    
    return(x_test1)


In [8]:
X = iris[['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width']]
y = iris[['Species']]

x_train, x_test, y_train, y_test = train_test_split( X, y, test_size = 0.5, stratify=y, random_state = 123)

#Checks
#Proportion in training data

print(y_train.Species.value_counts()/len(y_train))
print(y_test.Species.value_counts()/len(y_test))


versicolor    0.333333
virginica     0.333333
setosa        0.333333
Name: Species, dtype: float64
versicolor    0.333333
virginica     0.333333
setosa        0.333333
Name: Species, dtype: float64


### Enter the K value

In [9]:
kval=int(input("enter the value of k"))
df=runknn(kval,x_test,y_test,x_train,y_train)

enter the value of k5


In [10]:
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width        pred  \
14            5.8          4.0           1.2          0.2      setosa   
104           6.5          3.0           5.8          2.2   virginica   
75            6.6          3.0           4.4          1.4  versicolor   
3             4.6          3.1           1.5          0.2      setosa   
120           6.9          3.2           5.7          2.3   virginica   

         actual  
14       setosa  
104   virginica  
75   versicolor  
3        setosa  
120   virginica

In [11]:
df.actual.dtypes=="object"

True

In [15]:
from sklearn.metrics import confusion_matrix

if(df.actual.dtypes=="object"):
    c = confusion_matrix(df.pred, df.actual)
    print("confusion matrix")
    print(c)
    print("")
    
    #Overall Accuracy
    print("overall accuracy",(c[0,0]+c[1,1]+c[2,2])/np.sum(c)*100)
    
else:
    print("rmse value")
    print(np.sqrt(np.mean((df.pred - df.actual)**2)))

confusion matrix
[[25  0  0]
 [ 0 23  1]
 [ 0  2 24]]

overall accuracy 96.0


### Rough Work

In [108]:
obs1=x_test.head(1)
print(x_train.loc[98,]-obs1)

a=(x_train.loc[98,]-obs1)**2
print(a)

print(np.sum(a.values))
np.sqrt(np.sum(((x_train.loc[98,]-obs1)**2).values))

    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
14          -0.7         -1.5           1.8          0.9
    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
14          0.49         2.25          3.24         0.81
6.790000000000001


2.6057628441590768

In [144]:
y_train

Species    object
dtype: object

In [165]:
y_train.columns[0]

'Species'

In [166]:
if(y_train[y_train.columns[0]].dtypes=="object"):
    
    print(1)

1


In [167]:
c=pd.Series(["pear","orange","apple","orange","grape","wine","apple"])

In [118]:
c.dtypes

dtype('O')

In [119]:
type(c)

pandas.core.series.Series

In [56]:
a=[]

a.append(y_train.loc[[1,2,3],"Species"].head(1)[1])

In [85]:
c.count

<function list.count(value, /)>

In [120]:
max(c.values, key=list(c).count)

'orange'